public class GlobalConsts {
    public static final String ACCOUNT_SLA_GOLD = System.Label.AccountSLAGold;          
    public static final String ACCOUNT_PRIORITY_HIGH = System.Label.AccountPriorityHigh;    
    public static final String ACCOUNT_PRIORITY_LOW = System.Label.AccountPriorityLow;        
    public static final String ACCOUNT_INDUSTRY_BANKING = System.Label.AccountIndustryBanking;        
    public static final String ACCOUNT_ERROR_MESSAGE_PRIORITY_BEFORE_INSERT = System.Label.AccountSLAGoldPriorityErrorBeforeInsert; 
    public static final String ACCOUNT_ERROR_MESSAGE_PRIORITY_BEFORE_UPDATE = System.Label.AccountSLAGoldPriorityErrorBeforeUpdate;    
    public static final String ERROR_FETCHING_COMMITS = System.Label.ErrorMessageFetchCommits;
    public static final String ERROR_CREATING_REQUEST = System.Label.ErrorMessageCreatingRequest;
    public static final String ERROR_PROCESSING_RESPONSE = System.Label.ErrorMessageProcessingResponse;
    public static final String INVALID_STATUS_CODE = System.Label.InvalidStatusCode;
    public static final String ERROR_CREATING_CASE = System.Label.ErrorDuringCreatingCase;
    public static final String FETCH_COMMITS_ERROR = System.Label.FetchCommitsError;    
    public static final String CREATE_COMMITS_ERROR = System.Label.CreateCaseError;        
}
