public class GlobalConsts {
    public static final String ACCOUNT_SLA_GOLD = System.Label.AccountSLAGold;          
    public static final String ACCOUNT_PRIORITY_HIGH = System.Label.AccountPriorityHigh;    
    public static final String ACCOUNT_PRIORITY_LOW = System.Label.AccountPriorityLow;        
    public static final String ACCOUNT_INDUSTRY_BANKING = System.Label.AccountIndustryBanking;        
    public static final String ACCOUNT_ERROR_MESSAGE_PRIORITY_BEFORE_INSERT = System.Label.AccountSLAGoldPriorityErrorBeforeInsert; 
    public static final String ACCOUNT_ERROR_MESSAGE_PRIORITY_BEFORE_UPDATE = System.Label.AccountSLAGoldPriorityErrorBeforeUpdate;    
}
